### ISSUE TITLE
Lokalsystematik Rechtswissenschaften: Knoten mit Notation ohne Label

### ISSUE THREAD

**Issue by SArndt-TIB** [runnwerth/TIBLokalsystematiken#1]
In der Excel-Tabelle der Lokalsystematik gibt es Knoten, die zur Strukturierung verwendet werden, aber kein Label enthalten.

- [x] Klären, ob es sich dabei um einen Fehler handelt.

Dies betrifft:

030 - 059 <http://uricorn.fly/tib_lok_sys#jur-030-059>:
![grafik](https://user-images.githubusercontent.com/52701352/110327611-78419100-801a-11eb-91d9-638cbb533f37.png)

In der Online-Version der Aufstellungssystematik findet sich der Knoten jur 030 - 059 nicht:
![grafik](https://user-images.githubusercontent.com/52701352/110328509-b9867080-801b-11eb-96e8-82a9a251d568.png)

Seine untergeordneten Knoten werden der Überschrift von jur 020 - 029 zugeordnet - was vom Text her ebenfalls passt:
![grafik](https://user-images.githubusercontent.com/52701352/110328803-17b35380-801c-11eb-9c33-7360c6f181d1.png)

In der SKOS-Modellierung liegt im Vergleich dazu eine leicht abweichende hierarchische Modellierung vor:
![grafik](https://user-images.githubusercontent.com/52701352/110330543-28fd5f80-801e-11eb-8d43-125aff037e31.png)

Lösungsvorschlag:
- [x] Knoten jur-030-059 auf jetziger Ebene behalten, Label von jur-020-029 und jur-030-059 anpassen

692 - 692.3 <http://uricorn.fly/tib_lok_sys#jur-692-692.3>:
![grafik](https://user-images.githubusercontent.com/52701352/110327814-c2c30d80-801a-11eb-90ff-fada7f2d0439.png)

In der Online-Version der Aufstellungssystematik wird der Knoten nicht verwendet, jur 692.3 wird unter jur 692 - 692.2 gelistet, wo er auch hingehört:
![grafik](https://user-images.githubusercontent.com/52701352/110328182-4977ea80-801b-11eb-93ef-ebd6a73c71b6.png)

Eine Ebene weiter oben wird der Knoten jur 692 - 692.3 ausgelassen:
![grafik](https://user-images.githubusercontent.com/52701352/110328324-82b05a80-801b-11eb-80ba-504960829c3e.png)
 
- [x] Hierarchische Struktur abbilden wie in der Aufstellungssystematik im TIB-Portal
- [x] Notationssystem aktualisieren: 692-692.2 --> 692-692.3 
- [x] Notationssytem aktualisieren: 692-692.2 entfernen

Zugehöriger Query:
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
SELECT *
WHERE
{
?s a skos:Concept .
MINUS { ?s rdfs:label ?label} }
ORDER by ?s
```

**Comment by BrehmE4TIB** [comment]
Hallo, konnte die Lösungen nicht ankreuzen. Schicke die Exceltabelle in korrigierter Form, auch inkl. der Änderungen in der Systematik (neues issue). Änderungen und Korrekturen gelb markiert.

**Comment by SArndt-TIB** [comment]
Wie in der [aktualisierten Excel-Tabelle](https://github.com/runnwerth/TIBLokalsystematiken/blob/main/Originaldateien/Kopie%20von%20FBR-Systematik_Umsetzung_Stand%2020210309%20Masterdatei.xls) dokumentiert in SKOS umgesetzt. Issue ist damit behoben.
