### ISSUE TITLE
Lokalsystematik Rechtswissenschaften: Knoten mit mehreren Label

### ISSUE THREAD

**Issue by SArndt-TIB** [runnwerth/TIBLokalsystematiken#3]
Einige Knoten haben mehrere Label, resultierend aus #2 .

Betrifft:

<http://uricorn.fly/tib_lok_sys#jur-002>	
<http://uricorn.fly/tib_lok_sys#jur-003>	
<http://uricorn.fly/tib_lok_sys#jur-069>	
<http://uricorn.fly/tib_lok_sys#jur-070>	
<http://uricorn.fly/tib_lok_sys#jur-076-us>	
<http://uricorn.fly/tib_lok_sys#jur-109>	
<http://uricorn.fly/tib_lok_sys#jur-113>	
<http://uricorn.fly/tib_lok_sys#jur-199>	
<http://uricorn.fly/tib_lok_sys#jur-245>	
<http://uricorn.fly/tib_lok_sys#jur-260-267>	
<http://uricorn.fly/tib_lok_sys#jur-292>	
<http://uricorn.fly/tib_lok_sys#jur-326>	
<http://uricorn.fly/tib_lok_sys#jur-328>	
<http://uricorn.fly/tib_lok_sys#jur-374>	
<http://uricorn.fly/tib_lok_sys#jur-432>	
<http://uricorn.fly/tib_lok_sys#jur-456>	
<http://uricorn.fly/tib_lok_sys#jur-498>	
<http://uricorn.fly/tib_lok_sys#jur-522>	
<http://uricorn.fly/tib_lok_sys#jur-616>	
<http://uricorn.fly/tib_lok_sys#jur-688>	
<http://uricorn.fly/tib_lok_sys#jur-801>	
<http://uricorn.fly/tib_lok_sys#jur-822>	
<http://uricorn.fly/tib_lok_sys#jur-838>	
<http://uricorn.fly/tib_lok_sys#jur-853>	
<http://uricorn.fly/tib_lok_sys#jur-858>	
<http://uricorn.fly/tib_lok_sys#jur-873>	
<http://uricorn.fly/tib_lok_sys#jur-892>	
<http://uricorn.fly/tib_lok_sys#jur-908>

Zugehöriger Query:
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
SELECT DISTINCT ?s
WHERE
{
?s a skos:Concept ; rdfs:label ?a  , ?b.
filter (?a != ?b)
}
 ORDER by ?s
```

**Comment by SArndt-TIB** [comment]
Nach RS mit Fachreferent: Entsprechende Identifier trennen und Überschriften und Labels entsprechend zuordnen.

**Comment by SArndt-TIB** [comment]
Nach Bearbeitung von issue #2  bei allen gelöst bis auf bei jur 076-us.

@BrehmE4TIB : Die Stelle kommt auch in der Excel-Tabelle zweimal vor (Zeile 226 und Zeile 229) - handelt es sich hierbei um einen Fehler?
![grafik](https://user-images.githubusercontent.com/52701352/110781848-af0be700-8266-11eb-9d6b-5022d01872e2.png)

Müssten die beiden Stellen unterschiedliche Notationen haben? Welche muss geändert werden?

**Comment by BrehmE4TIB** [comment]
jur 076 us        Internationales Bankrecht kann gestrichen werden. Das ist eine (unbeabsichtigte durch dei Überarbeitung der Systematik bedingte Doppelung - ein Fehler).

**Comment by SArndt-TIB** [comment]
Danke @BrehmE4TIB , das Issue schließe ich damit.
