### ISSUE TITLE
Änderung Systemstellen jur 829.8, jur 823 und jur 823.8

### ISSUE THREAD

**Issue by BrehmE4TIB** [runnwerth/TIBLokalsystematiken#6]
neue Systemstelle: 
jur 829.8  Geheimnisschutz

Änderung folgende Systemstellen: 
jur 823 **Finanzierungsgeschäfte** 
jur 823.8 Sonstige **Finanzierungsgeschäfte**

Danke :)

**Comment by SArndt-TIB** [comment]
@BrehmE4TIB  Wurden alle aktualisiert bzw. hinzugefügt.
